### PR TITLE
Add French locales

### PR DESCRIPTION
**Pull request by shaffe-fr**
Hi,

This PR adds French translations.
Thanks for this much needed close to framework rich text editor!

Karel

### CODE REVIEW

**Comment by manogi** [comment]
Hello there - are you finished, should I merge? Thanks for your contribution!

**Comment by shaffe-fr** [comment]
Hello Manogi,
Sorry for the force pushes without the draft mode :/
Yes, I'm good with that PR.

**Comment by sysyl** [comment]
Hello, is there a way to trad those titles in the table field ?
Thank you in advance
Capture d’écran 2024-07-09 à 22 26 24

**Comment by shaffe-fr** [comment]
Hi, did you try to publish the locale and to add the buttons translations ?

**Pull request merged**
