### PR TITLE
edit_html button

### PR DESCRIPTION
**Pull request by tmorian**
Hey there, I added an additional button to toggle between the tiptap editor and a textarea that has the generated HTML. Changes to the HTML are synced to the tiptap editor

### CODE REVIEW

**Comment by manogi** [comment]
@tmorian Thank you for your contribution!

**Comment by manogi** [comment]
This is part of Version 0.5.0 now.

**Comment by rreynier** [comment]
Awesome, thanks @manogi!

**Comment by jornwildenbeest** [comment]
Hey!
When I try including an iframe through the edit_html button the hole page crashes, do you have any idea why? @tmorian @manogi

**Comment by manogi** [comment]
@jornwildenbeest  Hi there, for now I can only confirm this pretty serious bug. The iframe seems to be saved alright in the DB, but the crash of the Admin panel is severe.
It seems to be the preview of the content - it is truncated, and probably truncating it somewhere inside the iframe is not a good idea. 
I am thinking of changing the preview, but now I'm hesitant because some people might be relying on the truncating... probably the best would be to strip out the iframe completely in the preview (or replace it with some div saying "iframe").

**Comment by manogi** [comment]
@jornwildenbeest as a side note: I would be careful not to use the editor in too much of a "web page builder" way. It is supposed to be a rich text editor, like an alternative to trix. For web page building maybe the [Gutenberg](https://novapackages.com/packages/genealabs/nova-gutenberg)  package might be an idea (I have not tried it yet, though).

**Comment by manogi** [comment]
@jornwildenbeest last comment ;-): The [Flexible Content] (https://novapackages.com/packages/whitecube/nova-flexible-content) also seems like a good solution for web page building.

**Comment by jornwildenbeest** [comment]
@manogi Thanks for you response! I know it is supposed to be a rich text editor, I just needed an option to include a iframe so I thought maybe it is possible through the edit_html option,
So I forked your branch and added the iframe option for tiptap. 

So when you add the iframe with the edit_html option, then return to the normal preview it works as you can see here 
image

But like I said when you try to save it, it crashes for some reason.

**Comment by jornwildenbeest** [comment]
So it crashes in the preview view indeed

**Comment by manogi** [comment]
I will add a solution for the preview so that it won't crash. Would you like to create a pull request for your solution as well?

**Comment by jornwildenbeest** [comment]
Ofcourse, give me 5 min

**Comment by manogi** [comment]
Don't hurry - I have client work to do atm so I can only get back to this in a few hours.

**Comment by jornwildenbeest** [comment]
I created the pull request, could you let me know when you finished the preview so it won't crash?
This is also for a client of mine.

**Comment by manogi** [comment]
Sure, will do this today.

**Pull request merged**
